In [ ]:
import pandas as pd

df = pd.read_csv(r"../data/cleaned/online_retail_cleaned.csv",parse_dates=["InvoiceDate"])

df.shape

(397884, 11)

In [2]:
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Revenue,Year,Month
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850,United Kingdom,15.30,2010,12
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34,2010,12
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850,United Kingdom,22.00,2010,12
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34,2010,12
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34,2010,12

In [3]:
snapshot_date = df["InvoiceDate"].max() + pd.Timedelta(days=1)
snapshot_date

Timestamp('2011-12-10 12:50:00')

In [4]:
customer_df = df.groupby("CustomerID").agg(Recency=("InvoiceDate", lambda x: (snapshot_date - x.max()).days),Frequency=("InvoiceNo", "nunique"),Monetary=("Revenue", "sum")).reset_index()

customer_df.shape

(4338, 4)

In [5]:
customer_df.head()

   CustomerID  Recency  Frequency  Monetary
0       12346      326          1  77183.60
1       12347        2          7   4310.00
2       12348       75          4   1797.24
3       12349       19          1   1757.55
4       12350      310          1    334.40

In [6]:
customer_df.describe()

         CustomerID      Recency    Frequency       Monetary
count   4338.000000  4338.000000  4338.000000    4338.000000
mean   15300.408022    92.536422     4.272015    2054.266460
std     1721.808492   100.014169     7.697998    8989.230441
min    12346.000000     1.000000     1.000000       3.750000
25%    13813.250000    18.000000     1.000000     307.415000
50%    15299.500000    51.000000     2.000000     674.485000
75%    16778.750000   142.000000     5.000000    1661.740000
max    18287.000000   374.000000   209.000000  280206.020000

In [7]:
customer_df.sort_values("Monetary", ascending=False).head()

      CustomerID  Recency  Frequency   Monetary
1689       14646        2         73  280206.02
4201       18102        1         60  259657.30
3728       17450        8         46  194550.79
3008       16446        1          2  168472.50
1879       14911        1        201  143825.06

In [ ]:
customer_df.to_csv(r"../data/cleaned/customer_level_rfm_base.csv",index=False)

In [9]:
customer_df[customer_df["Frequency"] == 209]

     CustomerID  Recency  Frequency  Monetary
326       12748        1        209  33719.73